### PR TITLE
added TracingTransport for http.Client

### PR DESCRIPTION
**Pull request by mgarski**
* Added TracingTransport, an http.RoundTripper implementation for tracing HTTP requests
* Capped metadata for the request & response bodies to 64KB each
* Updated README & examples
* gofmt organized the imports for the files edited

### CODE REVIEW

**Comment by ranrib** [comment]
Thanks @mgarski ! this should also fix https://github.com/epsagon/epsagon-go/pull/54 right?

**Comment by mgarski** [comment]
You're welcome @ranrib ! This PR resolves this issue: https://github.com/epsagon/epsagon-go/issues/14

**Comment by ranrib** [comment]
Quick question - since this PR breaks the existing signature, is there a way to keep both the previous way and the new Tracing transport together? @mgarski

**Comment by ranrib** [comment]
> Quick question - since this PR breaks the existing signature, is there a way to keep both the previous way and the new Tracing transport together? @mgarski

We can also implement the backward  compatibility on this PR

**Comment by mgarski** [comment]
@ranrib I can restore the backwards compatibility, will push a commit later today

**Review by maorlx — APPROVED** [review]
Thanks!

**Pull request merged**
